### ISSUE TITLE
Distinguishable colors not working?

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#51] opened 2015-10-20 09:12 UTC
I saw the discussion here https://github.com/JuliaGraphics/Colors.jl/issues/18 about generating distinguishable colors. However, for me, this does not seem to work right now. For example:

![selection_019](https://cloud.githubusercontent.com/assets/1282691/10602875/44252bce-771b-11e5-96f1-51f765dc6e13.png)

Here there are for example two blue identical colors and two quite similar red/orange ones.

**Comment by KristofferC** [comment] 2015-10-20 09:20
Manually using the colors from `Colors.jl` gives better result:

![selection_020](https://cloud.githubusercontent.com/assets/1282691/10603108/80df813a-771c-11e5-8ce5-2b536ba82d76.png)

**Comment by tbreloff** [comment] 2015-10-20 12:23
I changed the way it works... it doesn't use distinguishable_colors
anymore.  I changed it to pick colors out of an arbitrary color gradient (I
didn't love the colors generated before, and keeping a finite list actually
broke Gadfly with too many series on one plot).  Right now it's using the
"rainbow" color gradient, but I could easily do the same thing with a
gradient generated from distinguishable_colors.  I need to make a couple
small changes, and then you could pick your own gradient and help me settle
on a good default.  I'll keep you posted.

**Comment by tbreloff** [comment] 2015-10-20 16:28
I put together an IJulia notebook on colors in Plots: https://github.com/tbreloff/Plots.jl/blob/dev/examples/palettes.ipynb.  I'd love input, as well as some suggestions for alternative palette generation.

**Comment by tbreloff** [comment] 2015-10-20 16:30
cc: @timholy  Tim: I'd love your opinion on color generation as well.

**Comment by timholy** [comment] 2015-10-20 16:57
I'm probably not the best person to comment, but I'll give a shout-out to three who know more than me.

The colors output by `distinguishable_colors`, in the end, come down to how different pairs of colors are judged by `colordiff`. The algorithm is:
- generate a long list of possible colors (the `candidate` variable in `distinguishable_colors`)
- start with an initialized list of chosen colors (the `seed` input to `distinguishable_colors`)
- from the candidates, pick the one that is most-distant from all previously chosen colors (this is where `colordiff` is crucial)
- iterate the step above this one until you've generated as many as have been requested.

So there are really only a few things that determine the returned colors: the seed, the candidates, and the `colordiff` algorithm.  @dcjones has done some nice work in limiting the candidate colors, e.g., to be of a restricted range of luminance (see the optional inputs to `distinguishable_colors`), and that improves the aesthetic appeal of the choices.

But if you're worried about "near-duplicates," perhaps the core issue is the colordiff algorithm. Over the last 100+ years, a lot of work has gone into measuring differences between colors, and sadly, I'm not a colorimetry expert. Other than some type-stability fixes, I've made no contributions whatsoever to `colordiff`.

According to git, it looks like @glenn-sweeney wrote most of `Colors/src/differences.jl`, with some contributions from @m-lohmann. I know from past conversations that both of them know a lot more about color than I do, so perhaps they can offer some insight.

**Comment by tbreloff** [comment] 2015-10-20 17:14
Thanks @timholy.  I see the [code in Gadfly here](https://github.com/dcjones/Gadfly.jl/blob/bec0570a808936a2a082e5d1b88ce64913ad0ec8/src/scale.jl#L506-L510).  I'll be honest that I don't fully understand what each of those arguments change... I'll try to dig into it more.

**Comment by m-lohmann** [comment] 2015-10-20 19:23
I think CIELAB or the DIN color spaces provide the most “euclidean” metrics for a good evaluation of color differences. CIEDE2000 would work, too, but it might be computationally too expensive.
So, LCHab should be uniform enough to provide a good metric for color difference computations; it’s just CIELAB using cylindrical coordinates.
The actual problem might come from the conversion via the deuteranopic simulation. As far as I know, also from reading other papers on color deficiency algorithms, the implemented algorithm is probably not the best way to guarantee a good equidistribution of colors. Color deficiency is a tricky topic, and I guess that this could be the main problem here.
Would `distinguishable_colors` without the deuteranopic step produce better results (to color normal persons)? If that’s the case, then maybe it would be a good idea to make the color deficiency simulation optional until a better solution for color deficiency friendly palettes is found.

**Comment by tbreloff** [comment] 2015-10-20 21:18
I think it defaults to skipping the deuteranopic step (since `transform = identity` by default).  I played around some more in that [palette notebook](https://github.com/tbreloff/Plots.jl/blob/dev/examples/palettes.ipynb)... I'm really curious which palettes you guys prefer...

Do you have any experience with the "husl" color space?

**Comment by m-lohmann** [comment] 2015-10-20 22:07
I had a look at the HUSL website, and from what I can tell, it’s also quite non-uniform. It’s basically LUV pressed into a number scheme to guarantee the colors stay inside the RGB gamut, if I understand the Python code properly. I don’t see anything that would guarantee perceptual uniformity. LUV is not particularly uniform in the first place, it’s just a slightly more uniform substitute for the Yxy chromaticity diagram. And it’s about the best you can get in terms of perceptual uniformity if you use only linear transformations, as MacAdam put it in his book.
HUSL would still not deal with the out-of-gamut problem properly, because it’s just mapping the straight RGB gamut borders to a circle, disregarding everything else, unless I completely misunderstood the inner workings of this color space.

Nevertheless, it would be interesting to test it as an alternative for `distinguishable_colors`, if there would be any noticeable improvement. And having another color space in the tool belt can’t be bad.

**Comment by timholy** [comment] 2015-10-21 01:26
@m-lohmann, good catch. Here's what I get: 
![image](https://cloud.githubusercontent.com/assets/1525481/10625388/4e993620-7768-11e5-884f-c62ffca94fb8.png)

with the current `Colors`, for which the line that generates the candidates is
```jl
    for h in hchoices, c in cchoices, l in lchoices
        candidate[j+=1] = LCHab(l, c, h)
    end
```

Here's what I get:
![image](https://cloud.githubusercontent.com/assets/1525481/10625418/a1b13dda-7768-11e5-962c-fc09cee5aa84.png)

if I first make sure that every color is representable as RGB:
```jl
    for h in hchoices, c in cchoices, l in lchoices
        rgb = convert(RGB, LCHab(l, c, h))
        candidate[j+=1] = convert(LCHab, rgb)
    end
```
To my eye, the second group looks much more distinguishable. Do others agree?

**Comment by tbreloff** [comment] 2015-10-21 02:39
I agree that it's better with that change, but I don't think it's quite ideal.  Using white as the seed (and then throwing it away, since it's the background color), I see:

![tmp](https://cloud.githubusercontent.com/assets/933338/10626099/bf7ba9de-7779-11e5-9a6a-77850ea392dc.png)


I like this one, which uses a predefined gradient with my "zvalue pattern" algorithm to pick infinitely from the gradient:

![tmp](https://cloud.githubusercontent.com/assets/933338/10626132/14c0fb88-777a-11e5-9eda-67c4e4f56e63.png)

I'm thinking that could be good for the default "white-enough" background, and if it's close to black, just lighten those colors.  If it's a strong hue (what's a good way to determine that?) then it could default to using the new distinguishable_colors with the background as the seed.

Thoughts?  Do you think a non-greedy distinguishable_colors algorithm would be much better?  What if the algorithm treated contrast with a background color differently than it treated hue-difference with the other colors?

**Comment by timholy** [comment] 2015-10-21 11:45
>  I don't think it's quite ideal

Aesthetically or in terms of their distinguishability?

> I like this one, which uses a predefined gradient with my "zvalue pattern" algorithm to pick infinitely from the gradient

Those do look like good color choices. Roughly speaking they seem to be of similar luminance and relatively high chroma; if you want to develop a bit more intuition for those parameters, [this page](http://davidjohnstone.net/pages/lch-lab-colour-gradient-picker) has a widget you can play with (set the number of stops to 1 and choose Lch).

But certainly your algorithm seems great, and might be much faster than distinguishable_colors. I'd think it would be fine to add that algorithm to Colors, if you'd like.

**Comment by tbreloff** [comment] 2015-10-21 12:14
Aesthetically. My needs are a little more, since I want high contrast with a background, good looking initial colors, and I want each color to have similar "pull" to the eye (ie I don't want any colors to blatantly stand out... Not sure the correct terminology)

I'll look at that link and see if I can generalize those goals as part of the algorithm. 

As for contributing to Colors... Would you like to look through src/colors.jl and let me know if any of that looks Colors-worthy?

**Comment by KristofferC** [comment] 2015-10-21 19:39
I know nothing about theory of colors but in my subjective view the one that I liked most aesthetically is this one:

![image](https://cloud.githubusercontent.com/assets/1282691/10647832/0e6d1f70-783b-11e5-9c3e-8dec0464c27a.png)

To me, none of the colors there really stick out. However, I do think that the 3 blue ones and the orange/redish ones are quite similar to each other. More similar than any of the ones in for example:

![image](https://cloud.githubusercontent.com/assets/1282691/10647915/ad95877c-783b-11e5-9d65-ead53fe1c415.png)

For some reason it always to me seems like I think the blue colors are similar to each other. Maybe I am just bad at distinguishing blue nuances...

**Comment by tbreloff** [comment] 2015-10-21 19:47
A couple things:
- I think it's a fact that blues are harder to distinguish, which is why distance in RGB space will never be as good as distance in other spaces. 
- The last 5 colors in the second example are really hard to see on a white background, so it's not enough that they're different from the first ones.

I think the best of all worlds might be a distinguishable colors algorithm that can account for background color, seed colors, as well as some parameter to determine how much the colors can "stand out" from each other.  I'm not sure how much effort that is...

**Comment by timholy** [comment] 2015-10-21 20:03
Again, just constrain `luma` and `chroma` and I suspect you'll get most of these things you want. High luma + low chroma = white, which is what you're trying to avoid.

But also again, plenty of room for additional algorithms. I took a very brief glance through your src/colors.jl. IIRC there's some redundancy with stuff in Colors.jl, but it also looks like there are some good tools in there. Two brief comments:

- not sure where you got the "color lists" or palettes from, are there any license concerns?
- names like `getPaletteUsingFixedColorList` leave a little to be desired.

I'd encourage you to put together a PR.

**Comment by tbreloff** [comment] 2015-10-21 20:14
> are there any license concerns?

That's a good question.  Honestly I don't know anything about "color licensing".  Where do I begin?  Are there general rules to follow, or some way that licenses are registered?  If I can't remember where I saw something, but think I probably got inspiration from an online source, should I just delete the colors to be safe?

> names like getPaletteUsingFixedColorList leave a little to be desired

no argument here!

**Comment by m-lohmann** [comment] 2015-10-21 20:30
The problem is partly because the blue region is this weird thing poking out like a tail in CIELAB color space. Blue colors aren’t the strength of CIELAB, there is a considerable lack of hue “stability” in the blue region.
The dashed line is the border of the sRGB gamut:

![lab gamut ips235](https://cloud.githubusercontent.com/assets/7064307/10649203/040b89c4-7843-11e5-980d-d7d35f029688.png)

The same in DIN99o/DIN99c:

![din99o gamut ips235](https://cloud.githubusercontent.com/assets/7064307/10649223/2702c488-7843-11e5-95c2-a19f6c42f053.png)

**Comment by tbreloff** [comment] 2015-10-22 15:29
I took in all your comments, thought on it, and came up with a good solution that uses both the distinguishable_colors algo and my zvalues algo to generate an infinite palette that fits my requirements.  Here's most of the new code:

```
function adjust_lch(color, l, c)
    lch = LCHab(color)
    convert(RGB, LCHab(l, c, lch.h))
end

function lightness_from_background(bgcolor)
  bglight = LCHab(bgcolor).l
  0.45bglight + 55.0 * (bglight < 50.0)
end

function gradient_from_list(cs)
    zvalues = Plots.get_zvalues(length(cs))
    indices = sortperm(zvalues)
    sorted_colors = map(RGB, cs[indices])
    sorted_zvalues = zvalues[indices]
    ColorGradient(sorted_colors, sorted_zvalues)
end

function generate_palette(bgcolor = colorant"white";
                         color_bases = [colorant"steelblue", colorant"indianred"],
                         lightness = lightness_from_background(bgcolor),
                         n = 20)
    seed_colors = map(c -> adjust_lch(c,lightness,50), vcat(bgcolor, color_bases))
    colors = distinguishable_colors(20,
          seed_colors,
          lchoices=Float64[lightness],
          cchoices=Float64[50],
          hchoices=linspace(0, 340, 20)
        )[2:end]
    gradient_from_list(colors)
end
```

What this does is take in the background color, and a list of initial seed values, figures out a good lightness level, converts the seed colors and limits the candidate colors to that lightness, then generates a custom ColorGradient with the exact z-values which will perfectly match the first `n` generated colors.  After that it will infinitely pull from the gradient using my zvalue algorithm.

Here's some results:

![tmp](https://cloud.githubusercontent.com/assets/933338/10669567/60c003d6-78af-11e5-9f6a-27d4d8a83695.png)

![tmp](https://cloud.githubusercontent.com/assets/933338/10669588/768f33d0-78af-11e5-99dc-04cd77be54b1.png)

Thanks for all the help... what do you think?

(ps - I deleted a few of those pre-defined gradients that I wasn't sure about licensing, since I don't think I'll be using them anyways)

**Comment by tbreloff** [comment] 2015-10-23 14:36
I'm going to close this, but please keep the conversation going if there's more to say.  Thanks again for the insight.

**Closed by tbreloff** 2015-10-23 14:36 UTC
