### ISSUE TITLE
Julia crashes with PyPlot backend

### ISSUE THREAD

**Issue by baggepinnen** [tbreloff/Plots.jl#114] opened 2016-01-13 11:29 UTC
When producing plots with PyPlot as backend, julia crashes completely for me. 
In the example below, I have an array `T` with type as indicated. Plotting it works until the mouse hovers over the plot, when julia crashes. The same behavior is not present when importing PyPlot and plotting using PyPlot alone.  I have tried to run `Pkg.build("PyCall")` to ensure there is no error there, and it works fine.

```julia
typeof(T) = Array{Float64,3}
sum(isnan(T[:])) = 0
sum(isinf(T[:])) = 0

julia> T
4x4x200 Array{Float64,3}:
[:, :, 1] =
  0.331505  0.0367386   0.942738   0.113139 
  0.173482  0.979829   -0.0991875  0.0520452
 -0.927366  0.19643     0.318445   0.0806338
  0.0       0.0         0.0        1.0      

...

[:, :, 200] =
 -0.494345  -0.35601     0.79302   0.12962  
  0.233561  -0.933138   -0.273318  0.188193 
  0.837301   0.0501055   0.544442  0.0812398
  0.0        0.0         0.0       1.0      

julia> plot(T[:,:,1])
[Plots.jl] Initializing backend: pyplot

julia> Fatal Python error: PyEval_RestoreThread: NULL tstate

signal (6): Aborted
gsignal at /lib64/libc.so.6 (unknown line)
abort at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x7f9bd9a92f9e)
PyEval_RestoreThread at /usr/lib64/libpython2.7.so (unknown line)
unknown function (ip: 0x7f9bd0e2c7c5)
TclInvokeStringCommand at /lib64/libtcl8.6.so (unknown line)
unknown function (ip: 0x7f9bd04feaf3)
TclNRRunCallbacks at /lib64/libtcl8.6.so (unknown line)
unknown function (ip: 0x7f9bd04fd585)
Tcl_EvalEx at /lib64/libtcl8.6.so (unknown line)
Tk_BindEvent at /lib64/libtk8.6.so (unknown line)
TkBindEventProc at /lib64/libtk8.6.so (unknown line)
Tk_HandleEvent at /lib64/libtk8.6.so (unknown line)
unknown function (ip: 0x7f9bd08ba9e4)
Tcl_ServiceEvent at /lib64/libtcl8.6.so (unknown line)
Tcl_DoOneEvent at /lib64/libtcl8.6.so (unknown line)
tcl_doevent at /local/home/fredrikb/.julia/v0.4/Tk/src/tkwidget.jl:20
tcl_doevent at /local/home/fredrikb/.julia/v0.4/Tk/src/tkwidget.jl:20
jlcall_tcl_doevent_22042 at  (unknown line)
jl_apply_generic at /work/fredrikb/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at stream.jl:693
unknown function (ip: 0x7f9dfba3e498)
unknown function (ip: (nil))
Aborted (core dumped)
bash-4.3$ 
```

System information
```julia
julia> versioninfo()
Julia Version 0.4.2-pre+12
Commit 9e598b6 (2015-11-19 02:34 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tbreloff** [comment] 2016-01-13 16:57
Was this a one-time occurrence, or is it reproducible?  Can you post the full output from the beginning of a fresh Julia session?  (or link to a Github Gist if it's really long)

**Comment by baggepinnen** [comment] 2016-01-14 11:47
I have managed to reduce the occurances to the following
It seems to happen if Winston is imported while plotting with Plots

Winston by itself works fine, as does Plots. The fact that Winston is imported with `import`and not `using` should ensure there are no conflicts?

```julia
/local/home/fredrikb> julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

julia> using Plots

julia> pyplot()
Plots.PyPlotPackage()

julia> import Winston

WARNING: deprecated syntax "AbstractVecOrMat{T} (" at /local/home/fredrikb/.julia/v0.4/Winston/src/Winston.jl:96.
Use "AbstractVecOrMat{T}(" instead.
WARNING: requiring "Dates" in module "Winston" did not define a corresponding module.
WARNING: module Winston should explicitly import * from Base

julia> plot([1,2])
[Plots.jl] Initializing backend: pyplot

julia> Fatal Python error: PyEval_RestoreThread: NULL tstate

signal (6): Aborted
gsignal at /usr/bin/../lib64/libc.so.6 (unknown line)
abort at /usr/bin/../lib64/libc.so.6 (unknown line)
unknown function (ip: 0x7f7eeafe7f9e)
PyEval_RestoreThread at /usr/lib64/libpython2.7.so (unknown line)
unknown function (ip: 0x7f7ee30d77c5)
TclInvokeStringCommand at /lib64/libtcl8.6.so (unknown line)
unknown function (ip: 0x7f7eeba96af3)
TclNRRunCallbacks at /lib64/libtcl8.6.so (unknown line)
unknown function (ip: 0x7f7eeba95585)
Tcl_EvalEx at /lib64/libtcl8.6.so (unknown line)
Tk_BindEvent at /lib64/libtk8.6.so (unknown line)
TkBindEventProc at /lib64/libtk8.6.so (unknown line)
Tk_HandleEvent at /lib64/libtk8.6.so (unknown line)
unknown function (ip: 0x7f7eed5359e4)
Tcl_ServiceEvent at /lib64/libtcl8.6.so (unknown line)
Tcl_DoOneEvent at /lib64/libtcl8.6.so (unknown line)
tcl_doevent at /local/home/fredrikb/.julia/v0.4/Tk/src/tkwidget.jl:20
tcl_doevent at /local/home/fredrikb/.julia/v0.4/Tk/src/tkwidget.jl:20
jlcall_tcl_doevent_21599 at  (unknown line)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
anonymous at stream.jl:693
unknown function (ip: 0x7f810ecf4ad3)
unknown function (ip: (nil))
Aborted (core dumped)
/local/home/fredrikb> 
```

**Comment by tbreloff** [comment] 2016-01-14 19:58
Ok I figured something like this was happening.

> The fact that Winston is imported with importand not using should ensure there are no conflicts?

This isn't true, since you are dealing with GUI frameworks which modify global (process) state and memory directly.  Likely you have either:

- Multiple instances of the same GUI framework corrupting each other's state
- Different versions of a GUI library loaded at the same time

Either way, it's a bad idea to mix and match multiple GUI libraries in the same Julia session.

Sorry this isn't a helpful post beyond "yeah that sucks".  Is it imperative that you use both PyPlot and Winston in the same session?

**Comment by tbreloff** [comment] 2016-02-03 14:37
I'm going to close this, as the issue is well beyond the scope of Plots.

**Closed by tbreloff** 2016-02-03 14:37 UTC
