### ISSUE TITLE
surface with pyplot backend

### ISSUE THREAD

**Issue by sivapvarma** [tbreloff/Plots.jl#364] opened 2016-06-30 01:18 UTC
![pyplot_surface](https://cloud.githubusercontent.com/assets/1314675/16473735/f68a4080-3e24-11e6-9ea5-11fd0e6941fd.png)

`surface(X, Y, z)` works with `gr` and `plotly` backends though.

```
surface(X, Y, (x, y)->x^2+y^2) # works with all backends
```
Is this a limitation of `pyplot` backend ?

**Comment by tbreloff** [comment] 2016-06-30 01:26
I'm not at a computer. I didn't even realize that a 2-argument linspace was
allowed. What does it return? Add a 3rd argument (#points) and see if that
works

**Comment by sivapvarma** [comment] 2016-06-30 05:15
`linspace(start, stop)`  gives `n=50`(by default) points between `start` and `stop` including the end points.

**Comment by mmagnuski** [comment] 2016-06-30 09:28
I can confirm this bug.
@sivapvarma for a quick workaround, if you use a function as the third arg - it works very well.
```julia
f(x, y) = x^2 + y^2
surface(X, Y, f)
```

**Comment by mmagnuski** [comment] 2016-06-30 09:29
Ah, sorry, didn't read your full post, you write that there.

**Comment by tbreloff** [comment] 2016-06-30 14:50
Yeah this is really weird... at first glance I don't see what's happening.  I'll have to dig into it more.  Note that Plotly handles both cases well (and it looks awesome :)   GR shows the surface, but the axis ranges are weird.  I suspect it's a bug with expanding the axis extrema:

![tmp](https://cloud.githubusercontent.com/assets/933338/16492621/6a4bded0-3eb0-11e6-80c8-a59e4e65a90a.png)

**Comment by tbreloff** [comment] 2016-06-30 16:50
The problem is that `z` is an Array{Any,2} and so it was being treated as a matrix of discrete values (which had a bug).  However this is bad, since we obviously don't want the floating point values in z to be treated like categories.

I'll need to add some checking that all elements are numbers, and I guess I can't depend on the type of the object.

**Comment by tbreloff** [comment] 2016-06-30 16:52
Also, the function version doesn't have this problem because it's explicitly cast to a Float64.

**Comment by tbreloff** [comment] 2016-06-30 19:36
This should be fixed on dev/master

**Closed by tbreloff** 2016-06-30 19:36 UTC
